---
- name: initial provision
  hosts: all
  sudo: no
  tasks:

    - name: "yum install packages"
      sudo: yes
      yum: name="{{ item }}" state=present
      with_items:
        - ntp
        - acpid
        - git
        - python-devel

    # uncomment below if you want to run yum update
    #- name: "yum update"
    #  sudo: yes
    #  yum: name=* state=latest

    - name: "set timezone UTC"
      sudo: yes
      command: /usr/bin/timedatectl set-timezone UTC

    - name: "enable services"
      sudo: yes
      service: name="{{ item }}" state=running enabled=yes
      with_items:
        - ntpd
        - acpid

    - name: "timedatectl use ntp"
      sudo: yes
      command: /usr/bin/timedatectl set-ntp true

    - name: "create bin directory"
      file: path=~/bin state=directory

    - name: "create dist directory"
      file: path=~/dist state=directory

    # assumes python 2.7.x is installed with base os
    - name: "download python pip"
      get_url: url=https://bootstrap.pypa.io/get-pip.py dest=~/dist/get-pip.py

    - name: "install python pip"
      sudo: yes
      command: python /home/vagrant/dist/get-pip.py

    - name: "grab sslyze repo"
      git: repo=https://github.com/nabla-c0d3/sslyze.git dest=~/dist/sslyze

    - name: "grab nassl repo"
      git: repo=https://github.com/nabla-c0d3/nassl.git dest=~/dist/nassl

    - name: "download zlib"
      get_url: url=http://zlib.net/zlib-1.2.8.tar.gz dest=~/dist/zlib-1.2.8.tar.gz

    - name: "extract zlib"
      unarchive: copy=no creates=~/dist/nasl/zlib-1.2.8/README src=~/dist/zlib-1.2.8.tar.gz dest=~/dist/nassl

    - name: "get openssl"
      get_url: url=https://www.openssl.org/source/old/1.0.2/openssl-1.0.2f.tar.gz dest=~/dist/openssl-1.0.2f.tar.gz
        sha256sum=932b4ee4def2b434f85435d9e3e19ca8ba99ce9a065a61524b429a9d5e9b2e9c

    - name: "extract openssl"
      unarchive: copy=no creates=~/dist/nasl/openssl-1.0.2f/README src=~/dist/openssl-1.0.2f.tar.gz dest=~/dist/nassl

    - name: "symlink openssl-1.0.2f to openssl"
      file: src=~/dist/nassl/openssl-1.0.2f dest=~/dist/nassl/openssl state=link

    - name: "build nassl"
      command: python ~/dist/nassl/build_from_scratch.py
      args:
        chdir: ~/dist/nassl
        creates: ~/dist/nassl/bin/

    - name: "install nassl python module"
      command: python ~vagrant/dist/nassl/setup.py install
      sudo: yes
      args:
        chdir: ~vagrant/dist/nassl

    - name: "symlink sslyze_cli.py to bin/sslyze_cli.py"
      file: src=~/dist/sslyze/sslyze_cli.py dest=~/bin/sslyze_cli.py state=link

