---
- name: initial provision
  hosts: all
  sudo: no
  tasks:

    - name: "yum install packages"
      sudo: yes
      yum: name="{{ item }}" state=present
      with_items:
        - ntp
        - acpid
        - git
        - python-devel

    # uncomment below if you want to run yum update
    #- name: "yum update"
    #  sudo: yes
    #  yum: name=* state=latest

    - name: "set timezone UTC"
      sudo: yes
      command: /usr/bin/timedatectl set-timezone UTC

    - name: "enable services"
      sudo: yes
      service: name="{{ item }}" state=running enabled=yes
      with_items:
        - ntpd
        - acpid

    - name: "timedatectl use ntp"
      sudo: yes
      command: /usr/bin/timedatectl set-ntp true

    - name: "create bin directory"
      file: path=~/bin state=directory

    - name: "create dist directory"
      file: path=~/dist state=directory

    # assumes python 2.7.x is installed with base os
    - name: "download python pip"
      get_url: url=https://raw.github.com/pypa/pip/master/contrib/get-pip.py dest=~/dist/get-pip.py

    - name: "install python pip"
      sudo: yes
      command: python /home/vagrant/dist/get-pip.py

    - name: "grab sslyze repo"
      git: repo=https://github.com/nabla-c0d3/sslyze.git dest=~/dist/sslyze

    - name: "grab nassl repo"
      git: repo=https://github.com/nabla-c0d3/nassl.git dest=~/dist/nassl

    - name: "download zlib"
      get_url: url=http://zlib.net/zlib-1.2.8.tar.gz dest=~/dist/zlib-1.2.8.tar.gz

    - name: "extract zlib"
      unarchive: copy=no creates=~/dist/nasl/zlib-1.2.8/README src=~/dist/zlib-1.2.8.tar.gz dest=~/dist/nassl

    - name: "get openssl"
      get_url: url=http://www.openssl.org/source/openssl-1.0.2d.tar.gz dest=~/dist/openssl-1.0.2d.tar.gz
        sha256sum=671c36487785628a703374c652ad2cebea45fa920ae5681515df25d9f2c9a8c8

    - name: "extract openssl"
      unarchive: copy=no creates=~/dist/nasl/openssl-1.0.2d/README src=~/dist/openssl-1.0.2d.tar.gz dest=~/dist/nassl

    - name: "build nassl"
      command: python ~/dist/nassl/buildAll_unix.py
      args:
        chdir: ~/dist/nassl
        creates: ~/dist/nassl/build/

    - name: "install nassl python module"
      command: python ~vagrant/dist/nassl/setup_unix.py install
      sudo: yes
      args:
        chdir: ~vagrant/dist/nassl

    - name: "symlink sslyze.py to bin/sslyze.py"
      file: src=~/dist/sslyze/sslyze.py dest=~/bin/sslyze.py state=link

